// React/BasePoint/react_cli/路由练习(首页-关于-新闻-消息)/src/pages/Home/Home.jsx
import React from 'react'
import { NavLink, Outlet } from 'react-router-dom'

export default function Home() {
    return (
        <div>
            <h2>Home组件内容</h2>
            <div>
                <ul className="nav nav-tabs">
                    <li>
                        <NavLink className="list-group-item" to="news">News</NavLink>
                    </li>
                    <li>
                        <NavLink className="list-group-item " to="/home/message">Message</NavLink>
                    </li>
                </ul>
                {/* 二级路由组件展示位置 */}
                <Outlet />
            </div>
        </div>
    )
}

// Vue3/Demo/三级路由案例/src/pages/Home/index.vue
<template>
    <h2>Home组件内容</h2>
    <div>
        <ul class="nav nav-tabs">
            <li><router-link to="/home/newsList" exact-active-class="active" class="list-group-item">NewsList</router-link></li>
            <li><router-link to="/home/message" active-class="active" class="list-group-item">Message</router-link></li>
        </ul>
        <div>
            <router-view></router-view>
        </div>
    </div>
</template>

<script lang="ts" setup>

</script>

<style scoped></style>
